export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "FlexTest";
export const MOCKARO_KEY = process.env.NEXT_PUBLIC_MOCKARO_KEY;
export const VERIFICATION_DURATION_MS = 15 * 60 * 1000;
export const RESEND_DURATION_MS = 30 * 1000;
export const REMOTE_URL = process.env.NEXT_PUBLIC_REMOTE_URL || "https://my.api.mockaroo.com/api/v2/remote";
export const Env = process.env.NEXT_PUBLIC_ENV || "development";
export const GEMINITOKEN = process.env.NEXT_PUBLIC_GEMINI_TOKEN
export const DEEP_SEEK_URL = process.env.NEXT_PUBLIC_DEEP_SEEK_URL
export const DEEP_SEEK_TOKEN = process.env.NEXT_PUBLIC_DEEP_SEEK_TOKEN
export const OPENAI_API_KEY = process.env.NEXT_PUBLIC_OPENAI_API_KEY
